# Checks all required variables are defined
---
- name: "Check if fqdn is defined"
  ansible.builtin.fail:
    msg: "The variable 'fqdn' is not defined."
  when: fqdn is not defined

- name: "Check if dockerComposeFilePath is defined"
  ansible.builtin.fail:
    msg: "The variable 'dockerComposeFilePath' is not defined."
  when: dockerComposeFilePath is not defined
