- name: "Update package lists"
  ansible.builtin.apt:
    update_cache: yes

- name: "Upgrade all packages"
  ansible.builtin.apt:
    upgrade: dist

- name: Check if reboot is required
  stat:
    path: /var/run/reboot-required
  register: reboot_required_check

- name: Collect reboot information
  set_fact:
    reboot_required: "{{ reboot_required_check.stat.exists }}"

- name: "Inform the user that the system is about to reboot"
  ansible.builtin.debug:
    msg: "The system is about to reboot now. Please wait..."
  when: reboot_required

- name: "Reboot the machine"
  ansible.builtin.reboot:
  when: reboot_required
