- name: Check
  hosts: main
  gather_facts: true

  tasks:
    - name: "Set variables"
      ansible.builtin.set_fact:
        timestamp_readable: "{{ lookup('pipe', 'date +%Y%m%d%H%M%S') }}"
      tags:
        - always

    - name: "Checks required variables are defined"
      ansible.builtin.import_tasks: ./tasks/checks_deploy_variables.yaml
      tags:
        - always

    - name: Ping host
      ansible.builtin.ping:

    - name: "Setup auditd"
      ansible.builtin.import_tasks: "./tasks/setup_auditd.yaml"
      become: true

    - name: "Apply all security specific configuration changes"
      ansible.builtin.import_tasks: "./tasks/apply_security.yaml"
      become: true

    - name: "Apply docker bench security"
      ansible.builtin.import_tasks: "./tasks/execute_docker-bench-security.yaml"
      become: true

    - name: "Apply lynis"
      ansible.builtin.import_tasks: "./tasks/execute_lynis.yaml"
      become: true
